--操作人员表
ALTER TABLE OPERATORS ADD WORKGROUP VARCHAR2(500);
alter table operators add UUID VARCHAR2(50);

-- 仓库调拨总库明细
ALTER TABLE CKDBDZKMX ADD DCKH VARCHAR2(50);
ALTER TABLE CKDBDZKMX ADD DRKH VARCHAR2(50);
ALTER TABLE CKDBDZKMX ADD ISCONFIRM NUMBER(1);
ALTER TABLE CKDBDZKMX ADD DBQRBZ NUMBER(1);


-- 盘点表增加字段
ALTER TABLE STOCKTAKINGDETAIL ADD PDYBH VARCHAR2(50);
ALTER TABLE STOCKTAKINGDETAIL ADD ISSTOCKTAKING NUMBER(10);

-- 修改FAHUO 字段类型
ALTER TABLE FAHUO ALTER COLUMN WMSISEXPORT VARCHAR2(50);
ALTER TABLE FAHUO ALTER COLUMN WMSRECORDSTATUS VARCHAR2(50);

-- 修改FHDZK 字段类型
ALTER TABLE FHDZK ALTER COLUMN WMSISEXPORT VARCHAR2(50);
ALTER TABLE FHDZK ALTER COLUMN WMSRECORDSTATUS VARCHAR2(50);

-- FAHUOHEAD |FHDZKHEAD 增加字段
ALTER TABLE FAHUOHEAD ADD WMSEXPORTMSG  VARCHAR2(500);
ALTER TABLE FHDZKHEAD ADD WMSEXPORTMSG  VARCHAR2(500);

-- GOODSPLACE 增加字段
ALTER TABLE GoodsPlace ADD IsForbidden NUMBER(1) ;
ALTER TABLE GoodsPlace ADD FORBIDDENDATE DATE ;
ALTER TABLE GoodsPlace ADD FORBIDDENGUID VARCHAR2(50) ;

--入库单修改
ALTER TABLE RKDZK ADD SJR VARCHAR2(50);
ALTER TABLE RKDZK ADD RKDZK DATE;
ALTER TABLE RKD ADD SJR VARCHAR2(50);
ALTER TABLE RKD ADD RKDZK DATE;
--同库调拨单 增加数量字段
ALTER TABLE TKDBJL ADD SL NUMBER(18,6);