




/****** Object:  Table [dbo].[TKDBJL]    Script Date: 2020/11/18 17:58:12 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TKDBJL](
	[GUID] [varchar](50) NOT NULL,
	[DRStockId] [varchar](50) NULL,
	[DCStockId] [varchar](50) NULL,
	[DRKH] [varchar](50) NULL,
	[DCKH] [varchar](50) NULL,
	[HH] [varchar](50) NULL,
	[PH] [varchar](50) NULL,
	[SL] DECIMAL(18,6) default 0,
	[DH] [varchar](50) NULL,
	[DBRQ] [datetime] NULL,
	[USERGUID] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[WMS_TASKGROUP]    Script Date: 2020/11/23 16:47:59 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WMS_TASKGROUP](
	[GUID] [varchar](50) NOT NULL,
	[CODE] [varchar](50) NULL,
	[NAME] [varchar](50) NULL,
	[CREATEDATE] [datetime] NULL,
	[OPERATORGUID] [varchar](50) NULL,
	[ISAUDITING] [bit] NULL,
	[AUDITINGGUID] [varchar](50) NULL,
	[AUDITINGDATE] [datetime] NULL,
	[ISPICKING] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[WMS_TASKGROUPDETAIL]    Script Date: 2020/11/23 16:48:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[WMS_TASKGROUPDETAIL](
	[GUID] [varchar](50) NOT NULL,
	[TASKGROUPGUID] [varchar](50) NULL,
	[FAHUOHEADGUID] [varchar](50) NULL,
	[NOTES] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
